apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# deploy the resources below in the following order
- gatekeeper/gatekeeper-ns.yaml
- gatekeeper/opa-gatekeeper-source.yaml
- gatekeeper/opa-gatekeeper-helmrelease.yaml
# a template must be installed prior to `kubectl api-versions` showing any content
- gatekeeper/k8scontainerlimits-template.yaml
- gatekeeper/k8scontainerlimits-constraint.yaml
# create the namespace that will contain the policy-controller
- policy-controller/system-policy-ns.yaml
- policy-controller/policy-controller-helmrepo.yaml
- policy-controller/policy-controller-release.yaml
