apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-controller-hr
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: system-policy
  releaseName: policy-controller
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: policy-controller
      version: 0.6.7
      sourceRef:
        kind: HelmRepository
        name: sigstore-helm-charts
        namespace: flux-system
      interval: 60m
  values:
    webhook.replicaCount: 1
